# Generated by Django 5.0 on 2024-06-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='end_league_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_league_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
