# Generated by Django 5.0.4 on 2024-06-21 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('player_image', models.ImageField(upload_to='league_image_media')),
                ('total_run', models.IntegerField(blank=True, null=True)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.league')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_App.team')),
            ],
        ),
    ]
