# Generated by Django 5.0.4 on 2024-06-21 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_type', models.CharField(choices=[('FIX', 'Fix')], default='FIX', max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_pools', to='My_App.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_pools', to='My_App.team')),
            ],
        ),
    ]
