# Generated by Django 5.0.4 on 2024-06-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0005_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='team_b',
        ),
        migrations.AddField(
            model_name='pool',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='player_name1',
            field=models.ManyToManyField(blank=True, null=True, related_name='player1_pools', to='My_App.player'),
        ),
        migrations.AddField(
            model_name='pool',
            name='player_name2',
            field=models.ManyToManyField(blank=True, null=True, related_name='player2_pools', to='My_App.player'),
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='team_name1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1_pools', to='My_App.team'),
        ),
        migrations.AddField(
            model_name='pool',
            name='team_name2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2_pools', to='My_App.team'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='entry_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
