# Generated by Django 5.0.4 on 2024-06-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0006_remove_pool_name_remove_pool_team_a_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='limit',
        ),
    ]
