# Generated by Django 5.0.4 on 2024-06-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0007_remove_pool_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='end_league_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='start_league_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
