# Generated by Django 5.0.4 on 2024-06-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0008_pool_end_league_date_pool_start_league_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='end_league_date',
            new_name='end_pool_date',
        ),
        migrations.RenameField(
            model_name='pool',
            old_name='start_league_date',
            new_name='start_pool_date',
        ),
    ]
