# Generated by Django 5.0.4 on 2024-06-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0010_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='pool_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pool_name1', to='My_App.pool'),
        ),
    ]
