# Generated by Django 5.0.4 on 2024-06-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0012_alter_pair_pool_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='league_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_pools', to='My_App.league'),
        ),
    ]
