# Generated by Django 5.0.6 on 2024-06-27 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0014_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('demo_image', models.ImageField(upload_to='demo_media')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('select_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.league')),
                ('select_player_A', models.ManyToManyField(blank=True, null=True, related_name='select_player_A', to='My_App.player')),
                ('select_player_B', models.ManyToManyField(blank=True, null=True, related_name='select_player_B', to='My_App.player')),
                ('select_team_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_B', to='My_App.team')),
                ('select_team_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_A', to='My_App.team')),
            ],
        ),
    ]
