# Generated by Django 5.0.6 on 2024-06-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0015_demo_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='demo',
        ),
    ]
