# Generated by Django 5.0.6 on 2024-06-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0017_add_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='select_team_2',
            new_name='select_team_B',
        ),
    ]
