# Generated by Django 5.0.6 on 2024-06-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0019_match_match_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='pool_id',
            new_name='pool_name',
        ),
    ]
