# Generated by Django 5.0.6 on 2024-06-29 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0020_rename_pool_id_pair_pool_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='pool_name',
            new_name='pool_id',
        ),
    ]
