# Generated by Django 5.0.6 on 2024-06-29 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0021_rename_pool_name_pair_pool_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pair',
            old_name='pool_id',
            new_name='pool_name',
        ),
    ]
