# Generated by Django 5.0.6 on 2024-06-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0022_rename_pool_id_pair_pool_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
