# Generated by Django 5.0.6 on 2024-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0025_captain_add_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain_add_pool',
            name='vice_captain',
            field=models.ManyToManyField(blank=True, related_name='vice_captain_name', to='My_App.player'),
        ),
    ]
