# Generated by Django 5.0.6 on 2024-07-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0027_remove_captain_add_pool_vice_captain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vice_Captain_Add_Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_start_date', models.CharField(blank=True, max_length=50, null=True)),
                ('match_display_name', models.CharField(blank=True, default='', max_length=255)),
                ('captain', models.ManyToManyField(blank=True, related_name='main_captain_name', to='My_App.player')),
                ('select_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.league')),
                ('select_player_A', models.ManyToManyField(blank=True, related_name='vice_captain_select_player_A', to='My_App.player')),
                ('select_player_B', models.ManyToManyField(blank=True, related_name='vice_captain_select_player_B', to='My_App.player')),
                ('select_team_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_captain_team_A', to='My_App.team')),
                ('select_team_B', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vice_captain_team_B', to='My_App.team')),
                ('vice_captain', models.ManyToManyField(blank=True, related_name='select_vice_captain', to='My_App.player')),
            ],
        ),
    ]
