# Generated by Django 5.0.6 on 2024-07-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0028_vice_captain_add_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_end_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
