# Generated by Django 5.0.6 on 2024-07-15 05:39

import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0029_match_match_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool_Declare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_run', django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=100)),
                ('player_declare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.player')),
                ('team_declare', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.team')),
            ],
        ),
    ]
