# Generated by Django 5.0.6 on 2024-07-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0030_pool_declare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool_declare',
            name='total_run',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
