# Generated by Django 5.0.6 on 2024-07-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0033_pair_with_captain_v_captain'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_with_captain_v_captain',
            name='player_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_with_v3', to='My_App.player'),
        ),
    ]
