# Generated by Django 5.0.6 on 2024-07-15 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0034_pair_with_captain_v_captain_player_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pair_with_captain_v_captain',
            new_name='Pair_with_captain_and_v_captain',
        ),
    ]
