# Generated by Django 5.0.6 on 2024-07-15 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0036_pair_select_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair_with_captain',
            name='select_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.match'),
        ),
        migrations.AddField(
            model_name='pair_with_captain_and_v_captain',
            name='select_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='My_App.match'),
        ),
    ]
