# Generated by Django 5.0.6 on 2024-07-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0037_pair_with_captain_select_match_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('modile_no', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='league_image_media')),
                ('wallet_amount', models.IntegerField()),
                ('winning_amount', models.IntegerField()),
            ],
        ),
    ]
