# Generated by Django 5.0.6 on 2024-07-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0040_remove_playerpair_match_remove_playerpair_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
