# Generated by Django 5.0.6 on 2024-07-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0041_alter_pair_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, default='unblock', max_length=10, null=True),
        ),
    ]
